[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install --no-cache-dir -r requirements-minimal.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "./start.sh"
