[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements-minimal.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "./start.sh"
