[build]
builder = "nixpacks"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.railway]
buildCommand = "pip install --no-cache-dir -r requirements-minimal.txt"
