import { useEffect, useRef, useState } from 'react'
import { Sparkles, Shield, FileText } from 'lucide-react'
import { cn } from '@/lib/utils'
import { trackTermsAccepted } from '@/analytics'

const TERMS_KEY = 'rovr_terms_accepted'

interface Props {
  onAccept: () => void
}

const SECTIONS = [
  {
    Icon: Sparkles,
    title: 'AI responses',
    body: 'Rovr is powered by large language models. Responses are generated by AI and may occasionally be incomplete, outdated, or incorrect. Always verify important information against official Adobe documentation before acting on it.',
  },
  {
    Icon: Shield,
    title: 'Data & privacy',
    body: 'Your questions are sent to Claude (Anthropic) for processing. Do not share sensitive, confidential, or personally identifiable information in your queries — including passwords, API keys, client data, or internal business information.',
  },
  {
    Icon: FileText,
    title: 'Usage',
    body: 'Rovr is provided for learning and exploration of Adobe Experience Cloud documentation. Usage is subject to fair use limits. Your query activity may be monitored for quality and abuse prevention.',
  },
]

export function TermsModal({ onAccept }: Props) {
  const [checked, setChecked] = useState(false)
  const modalRef = useRef<HTMLDivElement>(null)
  const checkboxRef = useRef<HTMLInputElement>(null)

  // Move focus to checkbox on open
  useEffect(() => {
    checkboxRef.current?.focus()
  }, [])

  // Focus trap + block Escape
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault()
        e.stopPropagation()
        return
      }

      if (e.key !== 'Tab' || !modalRef.current) return

      const focusable = Array.from(
        modalRef.current.querySelectorAll<HTMLElement>(
          'input:not([disabled]), button:not([disabled]), [tabindex="0"]'
        )
      )
      if (focusable.length === 0) return

      const first = focusable[0]
      const last = focusable[focusable.length - 1]

      if (e.shiftKey) {
        if (document.activeElement === first) {
          e.preventDefault()
          last.focus()
        }
      } else {
        if (document.activeElement === last) {
          e.preventDefault()
          first.focus()
        }
      }
    }

    document.addEventListener('keydown', onKeyDown, true)
    return () => document.removeEventListener('keydown', onKeyDown, true)
  }, [])

  const handleAccept = () => {
    if (!checked) return
    localStorage.setItem(TERMS_KEY, 'true')
    trackTermsAccepted()
    onAccept()
  }

  return (
    // Backdrop — scrollable on short viewports so the full modal is reachable
    <div
      className="fixed inset-0 z-50 overflow-y-auto"
      style={{ backgroundColor: 'rgba(0,0,0,0.6)' }}
      onPointerDown={(e) => e.stopPropagation()}
    >
      <div className="flex min-h-full items-center justify-center p-4">
        <div
          ref={modalRef}
          role="dialog"
          aria-modal="true"
          aria-labelledby="terms-heading"
          className="w-full max-w-[520px] max-h-[calc(100dvh-2rem)] flex flex-col bg-white rounded-2xl overflow-hidden shadow-xl"
          onPointerDown={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div
            className="flex-shrink-0 flex items-center gap-3 px-6 py-4"
            style={{ backgroundColor: '#14532D' }}
          >
            <img
              src={`${import.meta.env.BASE_URL}rovrlogo.png`}
              alt="Rovr"
              className="h-8 w-auto flex-shrink-0"
            />
            <span className="text-white font-semibold text-base">Rovr</span>
          </div>

          {/* Scrollable terms body */}
          <div className="flex-1 min-h-0 overflow-y-auto overscroll-contain px-6 py-6">
            <h2
              id="terms-heading"
              className="text-lg font-semibold text-slate-800 mb-5"
            >
              Before you begin
            </h2>

            <div className="space-y-0">
              {SECTIONS.map(({ Icon, title, body }, i) => (
                <div key={title}>
                  <div className="flex gap-3 py-4">
                    <Icon
                      className="w-5 h-5 flex-shrink-0 mt-0.5"
                      style={{ color: '#10B981' }}
                      aria-hidden="true"
                    />
                    <div>
                      <p className="text-sm font-semibold text-slate-700 mb-1">{title}</p>
                      <p className="text-sm leading-relaxed" style={{ color: '#374151' }}>
                        {body}
                      </p>
                    </div>
                  </div>
                  {i < SECTIONS.length - 1 && (
                    <hr style={{ borderColor: '#A7F3D0' }} />
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Footer — always visible: checkbox + submit */}
          <div
            className="flex-shrink-0 px-6 py-4 border-t bg-white"
            style={{ borderColor: '#A7F3D0' }}
          >
            <label
              htmlFor="terms-checkbox"
              className="flex items-start gap-3 cursor-pointer"
            >
              <input
                ref={checkboxRef}
                id="terms-checkbox"
                type="checkbox"
                checked={checked}
                onChange={(e) => setChecked(e.target.checked)}
                className="mt-0.5 h-4 w-4 flex-shrink-0 rounded"
                style={{ accentColor: '#10B981' }}
              />
              <span className="text-sm text-slate-700 leading-relaxed select-none">
                I have read and understood the above. I agree to use Rovr responsibly.
              </span>
            </label>

            <button
              onClick={handleAccept}
              disabled={!checked}
              className={cn(
                'mt-4 w-full py-2.5 px-7 rounded-lg text-sm font-medium transition-colors',
                checked
                  ? 'bg-[#14532D] text-white hover:bg-[#10B981] cursor-pointer'
                  : 'bg-[#D1D5DB] text-[#9CA3AF] cursor-not-allowed',
              )}
            >
              I agree
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
