/** Shared Tailwind classes for AdminPage light/dark styling */
export const adminUi = {
  page: 'min-h-screen w-full min-w-0 flex justify-center px-4 py-6 sm:px-6 sm:py-8 bg-slate-100 dark:bg-slate-950 text-slate-900 dark:text-slate-100',
  shell: 'w-full max-w-7xl mx-auto rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 shadow-xl overflow-hidden',
  header: 'bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800',
  headerTitle: 'text-sm font-semibold text-slate-800 dark:text-slate-100',
  headerLink: 'text-slate-400 hover:text-slate-600 dark:text-slate-500 dark:hover:text-slate-300',
  headerBtn: 'text-xs text-slate-500 hover:text-slate-700 px-3 py-1.5 rounded-lg hover:bg-slate-100 dark:text-slate-400 dark:hover:text-slate-200 dark:hover:bg-slate-800 transition-colors',
  headerBtnDanger: 'text-xs text-red-500 hover:text-red-700 px-3 py-1.5 rounded-lg hover:bg-red-50 dark:text-red-400 dark:hover:text-red-300 dark:hover:bg-red-950/40 transition-colors',
  tabNav: 'bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800',
  tabActive: 'border-blue-600 text-blue-600 dark:border-blue-400 dark:text-blue-400 font-medium',
  tabInactive: 'border-transparent text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200',
  card: 'bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-700',
  cardTitle: 'text-sm font-semibold text-slate-700 dark:text-slate-200',
  cardMuted: 'text-xs text-slate-400 dark:text-slate-500',
  statLabel: 'text-xs text-slate-500 dark:text-slate-400 uppercase tracking-wider',
  statValue: 'text-lg font-semibold text-slate-800 dark:text-slate-100 mt-1 break-all',
  statValueLg: 'text-2xl font-semibold text-slate-800 dark:text-slate-100 mt-1',
  sectionTitle: 'text-sm font-semibold text-slate-600 dark:text-slate-300',
  input: 'px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 text-xs focus:outline-none focus:border-blue-400 dark:focus:border-blue-500',
  inputLg: 'w-full px-3 py-2.5 rounded-lg border border-slate-200 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 text-sm focus:outline-none focus:border-blue-400 dark:focus:border-blue-500 focus:ring-1 focus:ring-blue-400 dark:focus:ring-blue-500',
  tableWrap: 'bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-700 overflow-x-auto',
  tableHead: 'border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/80',
  th: 'text-left px-4 py-2.5 text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider',
  thSort: 'text-left px-4 py-2.5 text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider cursor-pointer select-none hover:text-slate-700 dark:hover:text-slate-200',
  tr: 'border-b border-slate-100 dark:border-slate-800',
  td: 'px-4 py-3 text-slate-700 dark:text-slate-300',
  tdMuted: 'px-4 py-3 text-slate-500 dark:text-slate-400 text-xs',
  tdFaint: 'px-4 py-3 text-slate-400 dark:text-slate-500 text-xs whitespace-nowrap',
  empty: 'px-4 py-8 text-center text-sm text-slate-400 dark:text-slate-500',
  json: 'text-xs bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg p-3 overflow-auto max-h-96 text-slate-600 dark:text-slate-300',
  loginCard: 'bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-xl p-8 w-full max-w-sm',
  error: 'text-sm text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-950/40 rounded-lg px-3 py-2 mb-4',
  loading: 'text-sm text-slate-400 dark:text-slate-500',
} as const
