# Streamlit Secrets Configuration
# This file contains sensitive configuration data
# Add this file to .gitignore to keep it secure

# Admin Panel Authentication
ADMIN_PASSWORD = "Ritridoma@123"  # Change this to your preferred password

# Security Settings
ADMIN_SESSION_TIMEOUT = 3600  # 1 hour in seconds
ADMIN_MAX_ATTEMPTS = 3  # Maximum login attempts before lockout
ADMIN_LOCKOUT_DURATION = 900  # 15 minutes in seconds


